pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Installing Node.js"
  - script: |
      npm install
    displayName: 'npm install'
    workingDirectory: '$(System.DefaultWorkingDirectory)/services'
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/services'
      includeRootFolder: false
      archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish files'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      name: 'drop'